[phases.setup]
pkgs = ["python311", "gcc", "libgl1-mesa-glx", "libglib2.0-0", "libsm6", "libxext6", "libxrender-dev"]
cmds = ["python -m venv /opt/venv"]

[phases.install]
cmds = [
    "/opt/venv/bin/pip install -r requirements.txt",
    "/opt/venv/bin/pip install torch==2.0.1 --index-url https://download.pytorch.org/whl/cpu",
    "/opt/venv/bin/pip install torchvision==0.15.2 --index-url https://download.pytorch.org/whl/cpu",
    "/opt/venv/bin/pip install ultralytics==8.0.186"
]

[start]
cmd = "/opt/venv/bin/python app.py"