[phases.setup]
pkgs = ["python311", "gcc", "curl"]
cmds = ["python -m venv /opt/venv"]

[phases.install]
cmds = [
    "/opt/venv/bin/pip install flask==2.3.3 flask-cors==4.0.0 Pillow==10.0.0 numpy==1.24.3 opencv-python-headless==4.8.1.78 matplotlib==3.7.5 PyYAML==6.0.1",
    "/opt/venv/bin/pip install torch==2.0.1 --index-url https://download.pytorch.org/whl/cpu --no-deps",
    "/opt/venv/bin/pip install torchvision==0.15.2 --index-url https://download.pytorch.org/whl/cpu --no-deps",
    "/opt/venv/bin/pip install filelock>=3.0.0 typing-extensions>=4.10.0 networkx sympy requests tqdm scipy pandas seaborn psutil",
    "/opt/venv/bin/pip install ultralytics==8.0.186 --no-deps",
    "mkdir -p /app/weights",
    "curl -L --retry 3 --retry-delay 5 -H 'Accept: application/vnd.git-lfs+json' -o /app/weights/yolov8-best.pt https://github.com/Seishiru/skin-backend/raw/main/weights/yolov8-best.pt",
    "curl -L --retry 3 --retry-delay 5 -H 'Accept: application/vnd.git-lfs+json' -o /app/weights/yolonas-best.pth https://github.com/Seishiru/skin-backend/raw/main/weights/yolonas-best.pth",
    "curl -L --retry 3 --retry-delay 5 -H 'Accept: application/vnd.git-lfs+json' -o /app/weights/efficientdet-best.pth https://github.com/Seishiru/skin-backend/raw/main/weights/efficientdet-best.pth"
]

[start]
cmd = "/opt/venv/bin/python app.py"